### ISSUE TITLE
CLI tool shouldn't print the traceback on errors

### ISSUE THREAD

**Issue by gcbirzan** [gridai/gridai#101]
### Description

Currently, the CLI tool prints this on error:

```
$ grid logs test
Traceback (most recent call last):
  File "/home/gcbirzan/.local/bin/grid", line 8, in <module>
    sys.exit(main())
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/grid/cli/cli/grid_logs.py", line 37, in logs
    experiment = Experiment(experiment)
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/grid/cli/core/experiment.py", line 33, in __init__
    self.identifier = self._experiment_id_from_name(self.name)
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/grid/cli/core/experiment.py", line 65, in _experiment_id_from_name
    raise ResourceNotFound(
grid.cli.exceptions.ResourceNotFound: Experiment test does not exist
If you wish to fetch an experiment for somebody in your team, use <username>:<experiment-name> format
```

The exception should be printed (though a humanly readable version should also exist), and that's it.

### Motivation

The traceback for errors that are part of the normal operations provides absolutely no useful information.

**Comment by sunitaprakash** [comment]
@gcbirzan Thanks for reporting.  We are working on improving the CLI.
