### ISSUE TITLE
grid status --export does not work

### ISSUE THREAD

**Issue by gcbirzan** [gridai/gridai#104]
## 🐛 Bug

```$ grid status --export json
✔ Done!
┏━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━┓
┃ Run                     ┃           Project ┃  Status ┃    Duration ┃ Experiments ┃ Running ┃ Queued ┃ Completed ┃ Failed ┃ Stopped ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━┩
│ eggplant-antelope-378   │ gcbirzan/forecast │ running │ 0d-00:10:12 │           1 │       1 │      0 │         0 │      0 │       0 │
│ futuristic-aardwark-912 │ gcbirzan/forecast │ running │ 0d-03:51:48 │           1 │       1 │      0 │         0 │      0 │       0 │
└─────────────────────────┴───────────────────┴─────────┴─────────────┴─────────────┴─────────┴────────┴───────────┴────────┴─────────┘

30 Run(s) are not active. Use `grid history` to view your Run history.
Traceback (most recent call last):
  File "/home/gcbirzan/.local/bin/grid", line 8, in <module>
    sys.exit(main())
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/grid/cli/cli/grid_status.py", line 56, in status
    client.status(kind=kind, identifiers=observable, export=export, is_global=is_global)
  File "/home/gcbirzan/.local/lib/python3.9/site-packages/grid/cli/client.py", line 799, in status
    results_key = list(result.keys())[0]
AttributeError: 'list' object has no attribute 'keys'
```

Same happens for CSV.

### Expected behavior

A json export. Or a CSV one.

### Environment

 - OS (e.g., Windows): WSL 
 - CLI version: lightning-grid==0.3.82

**Comment by sunitaprakash** [comment]
@gcbirzan Thanks for reporting the issue. We will work on a fix. 
The workaround for this would be to use the Web UI to download CSV file from the Run's window
