### ISSUE TITLE
Fails to upload a huge dataset to datastore

### ISSUE THREAD

**Issue by akihironitta** [gridai/gridai#118]
## 🐛 Bug
I'm trying to upload a huge dataset (~1.5TB) to the datastore from a grid session, but it seems like the size of a dataset may be limited by one of the dependencies as found in https://github.com/psf/requests/issues/2717.

Is there any workaround to upload one huge dataset? or it is not supposed to use datastore with a huge dataset like in my case?

### Expected behavior
`grid datastore create --source data_dir/ --name datastore_name` successfully uploads a huge dataset.

### Current behavior
Fails to upload omitting the error message shown below.

### To Reproduce
```console
$ grid datastore create --source xview3/ --name xview3-full
GraphQL URL: https://platform.grid.ai:443/graphql
GraphQL URL: https://platform.grid.ai:443/graphql
upload ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0%
✘ Uploading datastore xview3-full (v3) datastore to S3...

            Whoops, your datastore creation failed!

            To resume, run:

            grid datastore resume xview3-full-v3
            
Error: Failed to upload datastore xview3-full. string longer than 2147483647 bytes
$ grid datastore resume xview3-full-v3
GraphQL URL: https://platform.grid.ai:443/graphql
GraphQL URL: https://platform.grid.ai:443/graphql
upload ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0%
✘ Uploading datastore xview3-full (v3) datastore to S3...

            Whoops, your datastore creation failed!

            To resume, run:

            grid datastore resume xview3-full-v3
            
Traceback (most recent call last):
  File "/home/jovyan/conda/lib/python3.8/site-packages/grid/cli/client.py", line 1802, in resume_datastore_session
    session.upload()
  File "/home/jovyan/conda/lib/python3.8/site-packages/grid/sdk/utils/datastore_uploader.py", line 476, in upload
    raise e
  File "/home/jovyan/conda/lib/python3.8/site-packages/grid/sdk/utils/datastore_uploader.py", line 445, in upload
    func()
  File "/home/jovyan/conda/lib/python3.8/site-packages/grid/sdk/utils/datastore_uploader.py", line 381, in _upload_parts
    uploader.upload()
  File "/home/jovyan/conda/lib/python3.8/site-packages/grid/sdk/utils/uploader.py", line 191, in upload
    future.result()
  File "/home/jovyan/conda/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/jovyan/conda/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/jovyan/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jovyan/conda/lib/python3.8/site-packages/grid/sdk/utils/uploader.py", line 164, in _upload_part
    etag = self.upload_s3_data(url, data, self.retries, self.backoff_factor)
  File "/home/jovyan/conda/lib/python3.8/site-packages/grid/sdk/utils/uploader.py", line 100, in upload_s3_data
    response = s.put(url, data=data)
  File "/home/jovyan/conda/lib/python3.8/site-packages/requests/sessions.py", line 602, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/jovyan/conda/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jovyan/conda/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/jovyan/conda/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/jovyan/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/jovyan/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/jovyan/conda/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/jovyan/conda/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/jovyan/conda/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/jovyan/conda/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/jovyan/conda/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/home/jovyan/conda/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/home/jovyan/conda/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/home/jovyan/conda/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes
Error: Failed to upload datastore xview3-full. string longer than 2147483647 bytes
```

### Environment

 - OS (e.g., Windows): Ubuntu
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version: 0.3.87

**Comment by sunitaprakash** [comment]
@akihironitta Thanks for the feedback.  I don't think there is a workaround for this. Will keep you posted once we have a fix for this.

**Comment by sunitaprakash** [comment]
@akihironitta 
The fix for this issue is now in production. Please let us know if you have any further issues here and appreciate your patience while we resolved the issue.

Thanks
Sunita

**Comment by akihironitta** [comment]
Thanks for your swift action! I'll make sure to let you know if any issue happens.
