### ISSUE TITLE
.gitignore and .gridignore files have unexpected constraints when running grid with --localdir

### ISSUE THREAD

**Issue by sxren** [gridai/gridai#122]
## 🐛 Bug

`.gitignore` and `.gridignore` files have unexpected constraints when running `grid` with `--localdir`.

### Expected behavior

A valid `.gitignore` or `.gridignore` file should not cause a failure when running `grid` with `--localdir`.

### Current behavior

When running `grid run --localdir <script>`

Given a `.gridignore` file containing:

```
# A
something

# B
something_else
```

the run unexpectedly fails when processing the `.gridignore` file.

```
Traceback (most recent call last):
  File "/home/vscode/.local/bin/grid", line 8, in <module>
    sys.exit(main())
  File "/home/vscode/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/vscode/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vscode/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vscode/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vscode/.local/lib/python3.8/site-packages/grid/cli/cli/grid_run.py", line 489, in run
    client.train(
  File "/home/vscode/.local/lib/python3.8/site-packages/grid/cli/client.py", line 591, in train
    package_path = repository.package()
  File "/home/vscode/.local/lib/python3.8/site-packages/grid/sdk/source_code/repository.py", line 77, in package
    if self.package_path.exists():
  File "/home/vscode/.local/lib/python3.8/site-packages/grid/sdk/source_code/repository.py", line 52, in package_path
    filename = f"{self.version}.tar.gz"
  File "/home/vscode/.local/lib/python3.8/site-packages/grid/sdk/source_code/repository.py", line 46, in version
    self._version = dirhash(path=self.path, algorithm="blake2", ignore=gridignore.generate(src=self.path))
  File "/home/vscode/.local/lib/python3.8/site-packages/grid/sdk/source_code/hashing.py", line 45, in dirhash
    for file in path.glob(pattern):
  File "/usr/lib/python3.8/pathlib.py", line 1116, in glob
    selector = _make_selector(tuple(pattern_parts))
  File "/usr/lib/python3.8/pathlib.py", line 450, in _make_selector
    pat = pattern_parts[0]
IndexError: tuple index out of range
```

Given a `.gridignore` file containing:

```
# A
something
# B
something_else
```

the run continues after processing the `.gridignore` file as expected.

### To Reproduce

- Add a `.gridignore` file to your directory containing:
```
# A
something

# B
something_else
```
- Run `grid run --localdir <script>`

### Environment

 - OS (e.g., Windows): Linux
 - Browser (e.g., Chrome, Safari): N/A
 - CLI version: 0.3.88

**Comment by luiscape** [comment]
Hi @sxren, it turns out that the issue takes place whenever there's a path that starts with / in any of those files.

This is being addressed now. We'll make a build with the changes shortly.

**Comment by sxren** [comment]
@luiscape This is a different issue.

**Comment by sxren** [comment]
Temporary fix.

Added `ln and` to `{ln for ln in raw_lines not ln.startswith("#")}` in `grid/sdk/source_code/gridignore.py#_read_and_filter`.

Before
```
def _read_and_filter(path: Path) -> Set[str]:
    """Reads ignore file and filter comments."""
    raw_lines = [ln.strip() for ln in path.open().readlines()]
    return {ln for ln in raw_lines not ln.startswith("#")}
```

After
```
def _read_and_filter(path: Path) -> Set[str]:
    """Reads ignore file and filter comments."""
    raw_lines = [ln.strip() for ln in path.open().readlines()]
    return {ln for ln in raw_lines if ln and not ln.startswith("#")}
```

**Comment by sxren** [comment]
```
>>> happy_pattern = str(Path(".gridignore").relative_to(Path()).parents[0] / "a_file")
>>> happy_pattern
"a_file"
>>> next(Path().glob(happy_pattern))
PosixPath('a_file')
```

```
>>> sad_pattern = str(Path(".gridignore").relative_to(Path()).parents[0] / "")
>>> sad_pattern
"."
>>> next(Path().glob(sad_pattern))
…
IndexError: tuple index out of range
```

**Comment by luiscape** [comment]
Great find, @sxren! :)

**Comment by luiscape** [comment]
@sxren this has now been implemented and will go out in our next release.
