### ISSUE TITLE
Cannot SSH to session - nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by bsridatta** [gridai/gridai#146]
## 🐛 Bug

I was able to ssh into the session and use the resource, all of a sudden I get the error "nodename nor servname provided, or not known". I created a new session, cleared all ssh related files, and did the steps again but it did not help. The debug log also showed "Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling".

### Expected behavior

Should be able to resolve the name and ssh

### Current behavior

Does not connect to the session. 

### To Reproduce

```
~ ❯ grid session ssh agile-kangaroo-399 -- -v                                                                                                                                                       

zsh: correct 'ssh' to '.ssh' [nyae]? n
Sync config for 1 interactive nodes
OpenSSH_8.6p1, LibreSSL 2.8.3
debug1: Reading configuration data /Users/sridattabudaraju/.ssh/config
debug1: /Users/sridattabudaraju/.ssh/config line 2: Applying options for agile-kangaroo-399
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to ae2946fd32f8c4f11bf914448b58788a-1434404723.us-east-1.elb.amazonaws.com port 22.
ssh: Could not resolve hostname ae2946fd32f8c4f11bf914448b58788a-1434404723.us-east-1.elb.amazonaws.com: nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/grid/bin/grid", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/grid/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/grid/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/grid/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/grid/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/grid/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/grid/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/grid/lib/python3.9/site-packages/grid/cli/cli/grid_session.py", line 394, in ssh
    subprocess.check_call(['ssh', node_name, *ssh_args])
  File "/opt/homebrew/Caskroom/miniforge/base/envs/grid/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', 'agile-kangaroo-399', '-v']' returned non-zero exit status 255.
~ ❯
```

### Environment

 - OS (e.g., Windows): Mac OS V.12.1
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version:  Grid CLI (0.7.4)

Any help into finding the problem will be very appreciated!

**Comment by sunitaprakash** [comment]
@bsridatta Thank you for reaching out to us. Our team will look into your ticket and get back to you shortly.
