### ISSUE TITLE
import cv2: ImportError libGL.so.1on grid run

### ISSUE THREAD

**Issue by sergeyshilin** [gridai/gridai#148]
## 🐛 Bug

Importing opencv (`import cv2`) in Python throws ImportError since it cannot locate libGL.so.1 library. 
Image affected: `grid-images__gpu-cuda10.2-cudnn8-devel-ubuntu18.04-py3.8-torch1.7.1-pl1.2.1`

### Expected behavior

As Pytorch Lightning works with images as well (e.g. cifar dataset), it is expected that importing opencv does not produce an error.

### Current behavior

Error is observed:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import cv2
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

### To Reproduce

requirements.txt:

```
opencv-python
```

main.py:

```python
import cv2

with open("output.txt", "w") as out_file:
    out_file.write("Hello world! \n")

print("Script is finished!")
```

Command to run:

```bash
grid run --name grid-test \
    --localdir \
    --instance_type 1_M60_8GB \
    --framework lightning \
    --gpus 1 \
    main.py
```

### Environment

 - OS (e.g., Windows): Linux fedora 5.16.14-200.fc35.x86_64
 - Browser (e.g., Chrome, Safari): --
 - CLI version: 0.8.8

### Additional context

Potentially, as a solution, the following can be added to the docker image:
```
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
```
(found [on stackoverflow](https://stackoverflow.com/a/63377623) but haven't tested it myself)

**Comment by sunitaprakash** [comment]
Hi! @sergeyshilin 
Thank you for reaching out to us. Our team will look into your ticket and get back to you shortly.

**Comment by sunitaprakash** [comment]
Hi! @sergeyshilin We will fixing this in the product. Like you mentioned above the potential solution is to use the Docker file.
**Command to do the run is** :
grid run --dockerfile Dockerfile main.py 

**Here is the sample Dockerfile:**
# base image you want to use
# make sure to use a CUDA image if running on GPUs
# FROM nvidia/cuda:XX.X-cudnnX-devel-ubuntuXX.XX
FROM python:3.9.6-slim

# these two lines are mandatory
WORKDIR /gridai/project
COPY . .

# any RUN commands you'd like to run
# use this to install dependencies
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install -r requirements.txt
