### ISSUE TITLE
Unable to SSH into interacive session

### ISSUE THREAD

**Issue by leifdenby** [gridai/gridai#42]
## 🐛 Bug

Tried connecting to interactive session via SSH. Got an error:

```bash
~> grid ssh-keys add lit_key ~/.ssh/id_ed25519.pub
Added key lit_key with id: 49f9916a-48b8-4c6b-9e36-9ded5fc3318c
~> grid interactive ssh nondescript-fox-131
Sync config for 1 interactive nodes
/home/earlcd/.ssh/config line 194: unsupported option "accept-new".
Traceback (most recent call last):
  File "/home/earlcd/anaconda2/envs/py36/bin/grid", line 10, in <module>
    sys.exit(main())
  File "/home/earlcd/anaconda2/envs/py36/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/earlcd/anaconda2/envs/py36/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/earlcd/anaconda2/envs/py36/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/earlcd/anaconda2/envs/py36/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/earlcd/anaconda2/envs/py36/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/earlcd/anaconda2/envs/py36/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/earlcd/anaconda2/envs/py36/lib/python3.7/site-packages/grid/cli/grid_interactive.py", line 357, in ssh
    subprocess.check_call(['ssh', node_name])
  File "/home/earlcd/anaconda2/envs/py36/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', 'nondescript-fox-131']' returned non-zero exit status 255.
```

### Environment

 - OS (e.g., Windows): linux, centos 7
 - Browser (e.g., Chrome, Safari): n/a
 - CLI version: v0.3.68
 - SSH version (`ssh -V`): OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017 

### Additional context

I think my `ssh` client is unhappy with the `StrictHostKeyChecking` in the entry added to my `~/.ssh/config`. Also, it would be nice if the script mentioned that it modifies `~/.ssh/config`.

Sorry to have found another :bug:

**Comment by luiscape** [comment]
@leifdenby you are absolutely right. For some reason, the SSH client that you are using doesn't support that option on CentOS (?!). Let me look into it. 

I the meantime, I think we may have a workaround. Let's chat on Slack.

**Comment by luiscape** [comment]
The `accept-new` option was added in 2017-10-03 on OpenSSH (see [release notes here](https://www.openssh.com/txt/release-7.6)). There were previous options that allowed for similar functionality. We'll find a solution for this one that considers that.

**Comment by sunitaprakash** [comment]
@leifdenby This has been fixed in the latest build, please update the CLI -> pip install lightning-grid --upgrade
