### ISSUE TITLE
Module missing `cli`. Not able to install grid-cli

### ISSUE THREAD

**Issue by bibinmjose** [gridai/gridai#52]
## 🐛 Bug

I am trying to install grid cli by defining a new conda environment on Windows : `pip install lightning-grid --upgrade`

### Current behavior

```
Traceback (most recent call last):
  File "D:\AppData\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\AppData\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\<username>\OneDrive\Documents\grid\gridenv\Scripts\grid.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'cli'
```

### To Reproduce

Steps to reproduce the issue

### Environment
```
conda list
# packages in environment at D:\AppData\envs\grid:
#
# Name                    Version                   Build  Channel
aiohttp                   3.6.2                    pypi_0    pypi
analytics-python          1.2.9                    pypi_0    pypi
appnope                   0.1.0                    pypi_0    pypi
async-timeout             3.0.1                    pypi_0    pypi
attrs                     20.2.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
boto3                     1.15.8                   pypi_0    pypi
botocore                  1.18.8                   pypi_0    pypi
ca-certificates           2021.4.13            haa95532_1
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20                pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
coolname                  1.1.0                    pypi_0    pypi
coverage                  5.3                      pypi_0    pypi
dataclasses-json          0.5.2                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
deprecated                1.2.10                   pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.0                    pypi_0    pypi
google-api-core           1.22.2                   pypi_0    pypi
google-auth               1.22.0                   pypi_0    pypi
google-cloud              0.34.0                   pypi_0    pypi
google-cloud-core         1.3.0                    pypi_0    pypi
google-cloud-storage      1.28.1                   pypi_0    pypi
google-resumable-media    0.5.1                    pypi_0    pypi
googleapis-common-protos  1.52.0                   pypi_0    pypi
gql                       3.0.0a0                  pypi_0    pypi
graphql-core              3.1.2                    pypi_0    pypi
humanize                  3.1.0                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        2.0.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
lightning-grid            0.3.70                   pypi_0    pypi
marshmallow               3.9.1                    pypi_0    pypi
marshmallow-enum          1.5.1                    pypi_0    pypi
more-itertools            8.5.0                    pypi_0    pypi
multidict                 4.7.6                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0
packaging                 20.7                     pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       21.0.1           py37haa95532_0
pipreqs                   0.4.10                   pypi_0    pypi
pluggy                    0.13.1                   pypi_0    pypi
pprintpp                  0.4.0                    pypi_0    pypi
prompt-toolkit            3.0.7                    pypi_0    pypi
protobuf                  3.13.0                   pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
py                        1.9.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygithub                  1.46                     pypi_0    pypi
pygments                  2.7.4                    pypi_0    pypi
pyjwt                     1.7.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.7.10               h6244533_0
python-dateutil           2.8.0                    pypi_0    pypi
pytz                      2020.1                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
requests                  2.24.0                   pypi_0    pypi
rich                      9.12.0                   pypi_0    pypi
rsa                       4.5                      pypi_0    pypi
s3transfer                0.3.3                    pypi_0    pypi
setuptools                52.0.0           py37haa95532_0
six                       1.15.0                   pypi_0    pypi
smmap                     3.0.4                    pypi_0    pypi
sqlite                    3.35.4               h2bbff1b_0
stringcase                1.2.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tornado                   6.0.4                    pypi_0    pypi
traitlets                 5.0.4                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
typing-inspect            0.6.0                    pypi_0    pypi
tzlocal                   2.1                      pypi_0    pypi
ulid-py                   1.1.0                    pypi_0    pypi
urllib3                   1.25.10                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                    pypi_0    pypi
websockets                8.1                      pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py37_0
wrapt                     1.12.1                   pypi_0    pypi
yarg                      0.1.9                    pypi_0    pypi
yarl                      1.6.0                    pypi_0    pypi
yaspin                    0.17.0                   pypi_0    pypi
zipp                      3.2.0                    pypi_0    pypi
```
 - Windows

**Comment by sunitaprakash** [comment]
@bibinmjose Support for Windows is coming! In the meantime use WSL as a work-around 
Check out the docs for more details l[https://docs.grid.ai/products/global-cli-configs/using-grid-with-windows-subsystem-for-linux-wsl](url)
