### ISSUE TITLE
grid yaml config actions are not running

### ISSUE THREAD

**Issue by cosmicBboy** [gridai/gridai#74]
## 🐛 Bug

My workflow requires using a pre-trained model that was the output of a prior run, and I configured the `actions.on_before_training` settings to download the artifacts before the training run.

This my grid yaml config:

```
compute:

  provider:
    credentials: ...
    region: us-east-1
    vendor: aws

  train:
    disk_size: 200
    instance: t2.2xlarge
    cpus: 7
    gpus: 0
    memory: 32G
    framework: lightning

    datastore_name: ...
    datastore_version: ...
    datastore_mount_dir: ...

    actions:
      on_image_build:
        - apt-get install wget -y
        - pip install lightning-grid
      on_before_training_start:
        - grid login --username ... --key ...
        - grid artifacts <run_name> --download_dir /artifacts || echo 'skip artifacts download'

```

### Expected behavior

This config was working a few days ago but stopped working yesterday. This is the output log of a run that worked:

```
Login successful. Welcome to Grid.
Downloading artifacts → ('merciful-frog-774-exp0',)
  merciful-frog-774-exp0 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00Restoring data from /gridai/project/lightning_logs to .

```

### Current behavior

These are the logs from my run:

```
2021/05/29 14:36:05 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
/opt/conda/lib/python3.8/site-packages/torchaudio/backend/utils.py:53: UserWarning: "sox" backend is being deprecated. T
he default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migra
te to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  warnings.warn(
[INFO] 2021-05-29 14:36:06,925:: starting training run
[INFO] 2021-05-29 14:36:06,929:: config: TrainingConfig(model_config=ModelConfig(layer_size=3, stack_size=3, input_chann
els=64, residual_channels=64), checkpoint_every=25, optimizer='Adam', learning_rate=0.0003, weight_decay=0.0, n_training
_steps=500, pretrained_model_path=PosixPath('/artifacts/cherry-perch-119-exp0/models/20210527151106/model.pth'), model_o
utput_path=PosixPath('models/20210529143606'), tensorboard_dir=PosixPath('training_logs'))
[INFO] 2021-05-29 14:36:06,929:: files: ['/kinetics_debug/train/breakdancing/MEguK5_ding.mp4', '/kinetics_debug/train/br
eakdancing/eB4wwvnXwrI.mp4', '/kinetics_debug/train/breakdancing/zkyRFux7BWc.mp4']
Traceback (most recent call last):
  File "movenet/trainer.py", line 212, in <module>
    model = train_model(config, batch_fps)
  File "movenet/trainer.py", line 93, in train_model
    model = torch.load(config.pretrained_model_path)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/artifacts/cherry-perch-119-exp0/models/20210527151106/model.pt
h'
```

### To Reproduce

Steps to reproduce the issue

### Environment

 - OS (e.g., Windows): MacOS
 - Browser (e.g., Chrome, Safari): NA
 - CLI version: 0.3.71

**Comment by sunitaprakash** [comment]
@cosmicBboy Thanks for reporting the issue. Sorry that the config is not working for you. We will investigate and get back to you.

**Comment by sunitaprakash** [comment]
@cosmicBboy This a known issue, we're aiming to have this fixed in the next release

**Comment by sunitaprakash** [comment]
@cosmicBboy The config actions.on_before_training issue has been fixed.
